### ISSUE TITLE
Question: Unable to start pgaudit_analyze - DB root does not exist

### ISSUE THREAD

**Issue by gowtham500** [pgaudit/pgaudit_analyze#12]
Hello team,

I am using below script to run pgaudit analyze as a service.

```
[Service]
User=postgres
Group=postgres
Type=simple
ExecStart=/bin/bash -c '/app/extensions/pgaudit_analyze/bin/pgaudit_analyze --user postgres --log-file /app/log/postgresql/pganalyze.log /var/log/postgresql/'
TimeoutStartSec=0
```

Postgresql config has been modified to output logs as csv.

The error I get in /app/log/postgresql/pganalyze.log is that db "root" does not exist.

I am running the service as postgres user.

```
reading postgresql-12-main.csv
DBI connect('dbname=root;port=5432;','postgres',...) failed: FATAL:  database "root" does not exist at /app/extensions/pgaudit_analyze/bin/pgaudit_analyze line 166.
 at /app/extensions/pgaudit_analyze/bin/pgaudit_analyze line 44, <$hFile> line 1098.
        main::__ANON__('DBI connect(\'dbname=root;port=5432;\',\'postgres\',...) fail...') called at /usr/share/perl5/vendor_perl/Carp.pm line 100
        Carp::croak('DBI connect(\'dbname=root;port=5432;\',\'postgres\',...) fail...') called at /usr/lib64/perl5/vendor_perl/DBI.pm line 683
        DBI::__ANON__(undef, undef) called at /usr/lib64/perl5/vendor_perl/DBI.pm line 739
        DBI::connect('DBI', 'dbi:Pg:dbname=root;port=5432;', 'postgres', undef, 'HASH(0x21effe0)') called at /app/extensions/pgaudit_analyze/bin/pgaudit_analyze line 166
        main::databaseGet('root') called at /app/extensions/pgaudit_analyze/bin/pgaudit_analyze line 693
        eval {...} called at /app/extensions/pgaudit_analyze/bin/pgaudit_analyze line 649


```

If i run the command directly within the postgres user shell, i get the same error.

Can you please help me in resolving this issue.

**Comment by gowtham500** [comment]
@dwsteele  Can you please help on this issue

**Comment by dwsteele** [comment]
Well, it looks like you are auditing a database called "root" so pgaudit_analyze is expecting to be able to connect to it. Perhaps you are automatically creating a database as the current user, i.e. `root` when you run as a service?

**Comment by floptical** [comment]
Hi, I know this is closed but I'm getting this same issue and it's driving me insane.

Why isn't there an option to point pganalyze at a specific database?

What makes pganalyze expect a certain database?

The user I have it logging in as is "pganalyze" whos default database is "testing", yet it still throws an error about connecting to a non-existent "root" database.
