### ISSUE TITLE
pgaudit_analyze process filling up audit log file

### ISSUE THREAD

**Issue by Panha237** [pgaudit/pgaudit_analyze#4]
I have several databases in the PostgreSQL instance and created the extension and setup the pgaudit analyzer for these database, including the postgres database.

After starting the pgAudit Analyze as a daemon process, ./pgaudit_analyze --daemon /var/lib/postgresql/9.6/main/pg_log/ 
the log file and the csv file are filling up very fast (1mb per sec) continuously.
The files are filling up with the following continuously:

Regards,
Panha

**Comment by dwsteele** [comment]
Seems you forgot to append the log?

**Comment by Panha237** [comment]
What log that I need to append?
pgaudit_analyze log or pg_log?

**Comment by Panha237** [comment]
What log that I need to append?
pgaudit_analyze log or pg_log?

**Comment by dwsteele** [comment]
You ended your post with `The files are filling up with the following continuously:`  which made me think you were going to append something.  What is the log filling up with?

**Comment by Panha237** [comment]
Let me describe my activity:
I have configure master/standby  replication which enable pgaudit on master server. I test to insert data to some tables and view log on pg_log with command tail -f postgres-9.6.main.csv.
I see it keep writing log to pgaudit.log_event.

**Comment by dwsteele** [comment]
Make sure the role that is writing audit entries to the database is not audited.  You can do this by with `alter role pgaudit_etl set pgaudit.log = none`.  Or by setting specific roles to be audited.
