### ISSUE TITLE
pgaudit_analyze - unable to open log file

### ISSUE THREAD

**Issue by rishmax** [pgaudit/pgaudit_analyze#5]
Hi .. Greetings!!!...
I have configured pgaudit successfully and I can see the change in the log files. 
After that I followed the steps to configure pgaudit_analyze, did the modification in the postgresql.conf file, executed the audit.sql file (all objects created in the database).
Now when I am running following command:

./pgaudit_analyze --daemon <path to pg_log>

I am getting following error:

_Unable to open log file: Permission denied at ./pgaudit_analyze line 633
 at ./pgaudit_analyze line 44
        main::__ANON__('Unable to open log file: Permission denied at ./pgaudit_analy...') called at /usr/share/perl5/Carp.pm line 45
        Carp::confess('Unable to open log file: Permission denied') called at ./pgaudit_analyze line 633_

I have checked the permission set of the logs in pg_log, they all are owned by postgres user.

I really appreciate any help.

**Comment by rishmax** [comment]
Guys.. Please help me out.. it is urgent. We are in the middle of deployment of our application.

**Comment by dwsteele** [comment]
The pgaudit_analyze log defaults to /var/log/pgaudit_analyze.log.  If that location does not exist or is not writable to pgaudit_analyze you can specify another log location with `--log-file`.

**Comment by rishmax** [comment]
Thank you very much dwsteele for your response.

 I tried that too with following command:
 ./pgaudit_analyze --port 5488 --user postgres --log-file /app/logs/ppgolot10/pgaudit_analyze.log_

and now I am getting following error:

_log path must be passed at ./pgaudit_analyze line 619
 at ./pgaudit_analyze line 44
        main::__ANON__('log path must be passed at ./pgaudit_analyze line 619\x{a}') called at /usr/share/perl5/Carp.pm line 45
        Carp::confess('log path must be passed') called at ./pgaudit_analyze line 619_

===============
I have checked the permission to the log directory, it is 755 for postgres user.
Is there anything else we need to do ?

Appreciate your help.

**Comment by dwsteele** [comment]
You still need to pass the postgresql log directory as the final parameter.
```
/pgaudit_analyze --log-file=/app/logs/pgaudit_analyze.log /app/logs/postgresql
```
I can see this isn't very clear.  I'll update the help to make this more obvious.

**Comment by dwsteele** [comment]
I added a clarification to the help in 70b1057896 and the error message was improved in 197cbc0bc87.
