### ISSUE TITLE
It Does not work with postures-11 /Segmentation Fault 

### ISSUE THREAD

**Issue by rajatdey80** [pgaudit/pgaudit_analyze#8]
While configuring [root@postgressql-demo bin]# ./pgaudit_analyze  --daemon /var/lib/pgsql/11/data/log
Segmentation fault
[root@postgressql-demo bin]#
I can see following in /var/log/message 
ar 15 08:06:38 postgressql-demo systemd: Started PostgreSQL 11 database server.
Mar 15 08:23:43 postgressql-demo kernel: pgaudit_analyze[15126]: segfault at 0 ip 00007feebc1ae05f sp 00007ffed81b23b8 error 4 in libc-2.17.so[7feebc068000+1c2000]

**Comment by dwsteele** [comment]
It's pretty unusual for Perl to segfault like that -- I'd say you have some mismatched library versions installed, in particular libc.
