### ISSUE TITLE
pgaudit schema being audited

### ISSUE THREAD

**Issue by FcoHerrera** [pgaudit/pgaudit_analyze#9]
Hi David
Installed pgaudit/pgaudit_analyzer to a PostgreSQL 9.5 successfully, but when the analyzer daemon is running i see thousands of logs to the pgaudit schema tables by the user postgres

i tried to alter role the Postgres user to set the pgaudit.role to '' and pgaudit.log to none, but I see no effect in log files

the log grows very fast, 100Mb/min

This is the kind of log filling my logs as an example in pgaudit.log_event, but other pgaudit tables are being audited too, 

_2019-05-28 12:23:15.168 EST,"postgres","MYDB",5722,"[local]",5cec92b3.165a,91403524,"INSERT",2019-05-27 20:45:23 EST,3/22984457,190169372,LOG,00000,"AUDIT: SESSION,91403522,1,WRITE,INSERT,,,""insert into pgaudit.log_event (session_id, log_time, session_line_num, command, error_severity, sql_state_code,virtual_transaction_id, transaction_id, message, detail, hint, query, query_pos,
internal_query, internal_query_pos, context, location)
 values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)"",""5cec92b3.165a,2019-05-28 11:15:40.658-05,84846193,insert,log,00000,3/21340228,187976738,,,,,,,,,""",,,,,,,,,""_ 

any advice on how to correct this issue?  did I misconfigure something?

Thanks in advance

**Comment by FcoHerrera** [comment]
any advice?  :)

**Comment by dwsteele** [comment]
It's generally not a good idea to audit the `postgres` user.  Set `pgaudit.log=''` for `postgres` or only set `pgaudit.log` for users that you want to audit.
